# 사용할 베이스 이미지 지정
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# 애플리케이션 실행을 위한 명령어
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]